### ISSUE TITLE
replace call to /game/ships to just show stats no locations

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#45]

**Comment by HamishWHC** [comment]
How do we know where the ship will be when we purchase it then?

**Comment by ramonGonzEdu** [comment]
I concur with hamish on this one

**Comment by jadlers** [comment]
@artokun would you mind clarifying your thoughts behind this?

**Comment by nhowell** [comment]
I like the general direction of this idea. Maybe the game should start you off with a single "probe" ship or something at a designated "starting planet", where then you can start exploring, take out a loan, or buy a real ship.

Or, maybe better, the "user" has a headquarters where their person/company/corporation is based out of (which initially is located at a "starting planet"). In this case, maybe you don't need a starting "probe" ship, but instead can only start by purchasing a ship from that "starting planet" then have to start exploring/expanding from there. Then, like marketplaces, you'd need to have a ship at a location in order to view its available ships. Maybe the user's designated "headquarters" acts like a ship for the purposes of allowing visibility to available ships and the marketplace at that location, too.
