### ISSUE TITLE
throttle headers may be inaccurate

### ISSUE THREAD

**Issue by thebrubaker** [SpaceTradersAPI/issues-and-suggestions#52]
"How does the x-ratelimit-remaining header work? My thought was that it would be [0, x-ratelimit-limit) and if you made more requests after it got to 0 within the time window that you would get 429. However I've never seen this value above 1 and don't get a 429 even after making a few more requests past 0."

Looks like the throttle headers might not take into account the burst capability. Need to double check this.

**Comment by ericgroom** [comment]
This was my message, thanks for posting an issue I just realized I should have done that. 

Related to this, I've heard that different requests cost different amounts of points. Is the amount of points consumed consistent based on the method/path? It would be nice to have some kind of `x-points-consumed` header so that we could determine how many points a particular request consumes without having to do math on the points remaining at the start of the request vs the response. For instance I'm trying to write a rate limiter that allows concurrent requests so long as you stay within the point limit for a window.

**Comment by thebrubaker** [comment]
Great idea, exposing the points seems like a no brainer. It's a combo of 2/s and any spillover will deduct from an 8 per 10 second budget. So essentially you could send 28 requests over 10 seconds.

If anyone has some interesting modeling for what a good throttle rate / burst combo could be, we're definitely open to suggestions!

**Comment by ericgroom** [comment]
Ah okay, so the model is that you get 2 "free" requests per second and a budget for extra requests that gets renewed every 10 seconds. I don't think I've seen an explanation that simple, it should definitely be documented somewhere!

**Comment by Stumblinbear** [comment]
Rate limits appear to be working correctly, through a cursory test. How it works exactly should be documented, however.

**Comment by j-spacetrader-api** [comment]
Should be working now, will add to docs.
