### ISSUE TITLE
Ship cannot travel to planet it is currently on

### ISSUE THREAD

**Issue by thebrubaker** [SpaceTradersAPI/issues-and-suggestions#55]

**Comment by jadlers** [comment]
I'm guessing this issue is regarding the possibility of creating a flight plan to the same location which the ship is currently on. This should not be possible.

".efekts" provided an an image for the bug on Discord:
![image](https://user-images.githubusercontent.com/16165462/110327894-df5f4580-801a-11eb-9f6d-5fe52f26e22e.png)

**Comment by jadlers** [comment]
Fixed! Now gives the following error:
```json
{
    "error": {
        "code": 3003,
        "message": "Cannot process flight plan. Ship destination is same as departure."
    }
}
```
