### ISSUE TITLE
Marketplace endpoint has additional ships property in returned json

### ISSUE THREAD

**Issue by AppPackLtd** [SpaceTradersAPI/issues-and-suggestions#85]
From todays announcements:

> Made a few updates this evening
> 1. You will now get a little helpful message telling you how much fuel you need if you get an insufficient fuel error when creating a flight plan
> 2. /game/locations/:symbol will now also return a number of docked ships
> 3. /game/locations/:symbol/ships will return information about the docked ships like username, shipId and shipType

This seems to have caused the marketplace endpoint to also return the ships property on the resulting json. Although currently this appears to always be empty. Was it intended for this endpoint to return this additional data?

In my opinion this additional ships data should not be returned on the marketplace endpoint, and the additional property removed from the resulting json response.

**Comment by jadlers** [comment]
The ship property is included and no longer empty. The reasoning for having the ship returned is since its data is updated with a purchase/sell order. I'm closing this issue for now, should you feel like it's the wrong thing to do please feel free to elaborate on _why_ you don't think the ship should be returned and we'll have a discussion about it.
